name: Continuous Integration

# 1. Define when the workflow will run
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# 2. Grant permissions required to run the workflow
permissions:
  contents: read


jobs:
  check_structure:
    name: Check Repository Structure
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository 
        uses: actions/checkout@v4

      - name: Validate Repository structure
        run: |
          echo "Checking repository structure..."
           ls -la
           echo "Validation complete!"
           
        

   
