name: Continuous Integration

# 1. Define when the workflow will run
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# 2. Grant permissions required to run the workflow
permissions:
  contents: read


jobs:
  check strucrture:
    name: Check Repository Structure
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository 
        uses: actions/checkout@v4

      - name: Check docs folder exists
       run: |
         if [ ! -d "docs" ]; then
           echo "Error: / docs folder does not exist!"
           exit 1
         fi
          
     
      - name: Check required files inside docs
        run: |
          if [ -z "$(ls -A docs)" ]; then
             echo "Error: /docs folder is empty!"
             exit 1
          fi   

   
